### ISSUE TITLE
tomlDecoder Error bei Quotes

### ISSUE THREAD

**Issue by philipp2310** [philipp2310/snips-bring-shopping#9]
meschmesch:
Funktioniert nicht mehr (hat mal eine Zeitlang funktioniert) pi@raspberrypi:/var/lib/snips/skills/snips-bring-shopping $ python action-Philipp.bring_shopping.py Traceback (most recent call last): File "action-Philipp.bring_shopping.py", line 170, in garuda = Garuda() File "/var/lib/snips/skills/snips-bring-shopping/snips_garuda.py", line 81, in __init__ snips_toml = toml.load(toml_file) File "/usr/local/lib/python2.7/dist-packages/toml/decoder.py", line 134, in load return loads(f.read(), _dict, decoder) File "/usr/local/lib/python2.7/dist-packages/toml/decoder.py", line 301, in loads raise TomlDecodeError("Unbalanced quotes", original, i) toml.decoder.TomlDecodeError: Unbalanced quotes (line 49 column 151 char 1142) Hast du eine Idee?

**Comment by philipp2310** [comment]
#10
